/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type OfSecondsToDelayAllowingMintingToOccurFromContractCreationDefaultsTo1Second = number | null;
export interface InstantiateMsg {
  admin?: string | null;
  ask_interval: number;
  base_delegation: Uint128;
  base_price: Uint128;
  collection_code_id: number;
  cooldown_cancel_fee: Coin;
  cooldown_timeframe: number;
  hooks_admin?: string | null;
  max_account_length: number;
  min_account_length: number;
  min_price: Uint128;
  mint_start_delay?: OfSecondsToDelayAllowingMintingToOccurFromContractCreationDefaultsTo1Second;
  trading_fee_bps: number;
  valid_bid_query_limit: number;
  verifier?: string | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  mint_and_list: {
    account: string;
  };
} | {
  pause: {
    pause: boolean;
  };
} | {
  update_config: {
    config: Config;
  };
} | {
  remove_ask: {
    token_id: string;
  };
} | {
  update_ask: {
    seller: string;
    token_id: string;
  };
} | {
  set_bid: {
    token_id: string;
  };
} | {
  remove_bid: {
    token_id: string;
  };
} | {
  remove_bids: {
    token_id: string;
  };
} | {
  checked_remove_bids: {
    token_id: string;
  };
} | {
  accept_bid: {
    bidder: string;
    token_id: string;
  };
} | {
  finalize_bid: {
    token_id: string;
  };
} | {
  cancel_cooldown: {
    token_id: string;
  };
} | {
  manage_hooks: ManageHooksAction;
} | {
  update_ownership: Action;
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type ManageHooksAction = {
  remove_ask_hook: string;
} | {
  add_ask_hook: string;
} | {
  add_bid_hook: string;
} | {
  remove_bid_hook: string;
} | {
  add_sale_hook: string;
} | {
  remove_sale_hook: string;
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export interface Config {
  public_mint_start_time: Timestamp;
}
export type QueryMsg = {
  ownership: {};
} | {
  collection: {};
} | {
  params: {};
} | {
  config: {};
} | {
  ask: {
    token_id: string;
  };
} | {
  asks: {
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  ask_count: {};
} | {
  asks_by_seller: {
    limit?: number | null;
    seller: string;
    start_after?: string | null;
  };
} | {
  bid: {
    bidder: string;
    token_id: string;
  };
} | {
  bids_by_bidder: {
    bidder: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  bids: {
    limit?: number | null;
    start_after?: string | null;
    token_id: string;
  };
} | {
  bids_sorted_by_price: {
    limit?: number | null;
    start_after?: BidOffset | null;
  };
} | {
  reverse_bids_sorted_by_price: {
    limit?: number | null;
    start_before?: BidOffset | null;
  };
} | {
  bids_for_seller: {
    limit?: number | null;
    seller: string;
    start_after?: BidOffset | null;
  };
} | {
  highest_bid: {
    token_id: string;
  };
} | {
  ask_hooks: {};
} | {
  bid_hooks: {};
} | {
  sale_hooks: {};
} | {
  cooldown: {
    token_id: string;
  };
};
export type Addr = string;
export interface BidOffset {
  bidder: Addr;
  price: Uint128;
  token_id: string;
}
export type SudoMsg = {
  update_params: {
    ask_interval?: number | null;
    base_delegation?: Uint128 | null;
    base_price?: Uint128 | null;
    cooldown_cancel_fee?: Coin | null;
    cooldown_duration?: number | null;
    max_account_length?: number | null;
    min_account_length?: number | null;
    min_price?: Uint128 | null;
    trading_fee_bps?: number | null;
  };
} | {
  update_account_collection: {
    collection: string;
  };
};
export type NullableAsk = Ask | null;
export interface Ask {
  id: number;
  seller: Addr;
  token_id: string;
}
export interface HooksResponse {
  hooks: string[];
}
export type ArrayOfAsk = Ask[];
export type NullableBid = Bid | null;
export interface Bid {
  amount: Uint128;
  bidder: Addr;
  created_time: Timestamp;
  token_id: string;
}
export type ArrayOfBid = Bid[];
export type NullablePendingBid = PendingBid | null;
export interface PendingBid {
  amount: Uint128;
  ask: Ask;
  new_owner: Addr;
  unlock_time: Timestamp;
}
export interface OwnershipForAddr {
  owner?: Addr | null;
  pending_expiry?: Expiration | null;
  pending_owner?: Addr | null;
}
export type Decimal = string;
export interface SudoParams {
  ask_interval: number;
  base_delegation: Uint128;
  base_price: Uint128;
  cooldown_duration: number;
  cooldown_fee: Coin;
  hooks_admin: string;
  max_account_length: number;
  min_account_length: number;
  min_price: Uint128;
  trading_fee_percent: Decimal;
  valid_bid_query_limit: number;
}