/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./AccountMinter.types";
import * as _1 from "./AccountMinter.client";
import * as _2 from "./AccountMinter.message-composer";
import * as _3 from "./Terp721Account.types";
import * as _4 from "./Terp721Account.client";
import * as _5 from "./Terp721Account.message-composer";
export namespace contracts {
  export const AccountMinter = { ..._0,
    ..._1,
    ..._2
  };
  export const Terp721Account = { ..._3,
    ..._4,
    ..._5
  };
}